### ISSUE TITLE
Armar un motor interactivo de fichaje de artículos

### ISSUE THREAD

**Issue by JCMiguel** [JCMiguel/repository-reviewer#12]
Podría ser interesante disponer de un comando que permita fichar artículos de forma interactiva. Es decir algo como:

```
prompt$ ./indexer.py --index-card --to=index.csv
Fichaje de artículos
 Ingrese los datos pedidos a continuación
 > Nombre de archivo: ...10-Giuste-2022-XAI Pandemics.pdf
 > Título: ...Explainable Artificial Intelligence Methods in Combating Pandemics: A Systematic Review
 > Autor(es): ...F. Giuste; W. Shi; Y. Zhu; T. Naren; M. Isgut; Y. Sha; L. Tong; M. Gupte; M. D. Wang
 > Medio de publicación: ...IEEE Reviews in Biomedical Engineering
 > Año de publicación: ...2022
 > Fecha de búsqueda: ...Nov 2022
 > Abstract: ... <copy-paste here>
 > Palabras clave: ...Explainable Artificial Intelligence, COVID-19, Explanation Generation, Explanation Representation, Explanation Evaluation, Medical Imaging, Electronic Health Records
 > Referencias importantes: ...
 > Fortalezas: ...
 > Debilidades: ...
 > Oportunidades: ...
¡Ficha generada con éxito!
```

Al guardar estos archivos en index.csv, luego se podría tener un comando que nos permita buscar una ficha en concreto, por nombre de archivo u otro campo:

```
prompt$ ./indexer.py --get-index-card 10-Giuste-2022-XAI Pandemics.pdf```
Ficha encontrada:
 > Nombre de archivo: 10-Giuste-2022-XAI Pandemics.pdf
 > Título: Explainable Artificial Intelligence Methods in Combating Pandemics: A Systematic Review
 > Autor(es): F. Giuste; W. Shi; Y. Zhu; T. Naren; M. Isgut; Y. Sha; L. Tong; M. Gupte; M. D. Wang
 > Medio de publicación: IEEE Reviews in Biomedical Engineering
 > Año de publicación: 2022
 > Fecha de búsqueda: Nov 2022
 > Abstract: <copy-paste here>
 > Palabras clave: Explainable Artificial Intelligence, COVID-19, Explanation Generation, Explanation Representation, Explanation Evaluation, Medical Imaging, Electronic Health Records
 > Referencias importantes:
 > Fortalezas:
 > Debilidades:
 > Oportunidades:
```

A futuro, incluso, podría utilizar este motor de comandos para poder iterar y obtener estadísticas entre todas las fichas registradas: cuántas veces aparece la palabra clave XAI, cuánto artículos son de tal autor, cuántos artículos son de 2019, etc.

**Comment by JCMiguel** [comment]
Se podría incluir, junto con los datos requeridos, informar si está leído o pendiente de revisión.

**Comment by bassimat** [comment]
Justo estaba leyendo la teoría en los apuntes de Metodología de la Investigación y dije: "La idea de Migue no estará relacionada a esto?"
**BINGO!**
Me parece excelente! Coincido en como clasificaste el issue también. Intentemos tenerlo para la [Primera entrega](https://github.com/JCMiguel/repository-reviewer/milestone/1)

Luego conversemos un poco más sobre la idea así le damos un marco de diseño, y nos ponemos manos a la obra
