### ISSUE TITLE
Corrección de maquetación de tabs en QuerierPage

### ISSUE THREAD

**Issue by JCMiguel** [JCMiguel/repository-reviewer#30]
Detectado en Pull Request #27

Al maquetar las pestañas de "Búsqueda Básica" y "Búsqueda Avanzada" en QuerierPage, se observa que el ancho no se ajusta al total disponible en la pantalla. Se debe corregir este punto para que la interfaz sea responsiva.

**Comment by JCMiguel** [comment]
Incorporado en Pull Request #38, pendiente cerrar.

**Comment by bassimat** [comment]
Se resuelve en el desarrollo del pull #33 (Listado de resultados en pantalla)
