### ISSUE TITLE
Implementar módulo para control de logs

### ISSUE THREAD

**Issue by bassimat** [JCMiguel/repository-reviewer#8]
Conversar si se justifica. En caso afirmativo, convendría hacerlo en las primeras instancias del desarrollo

**Comment by bassimat** [comment]
Referencia a Python Logging Module:
[https://www.logicmonitor.com/blog/python-logging-levels-explained](https://www.logicmonitor.com/blog/python-logging-levels-explained)

**Comment by JCMiguel** [comment]
Me parece una buena idea. Tengo un ejemplo de código. Lo voy a disponibilizar en una rama independiente.
